# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c1a90a9a1358363184a23428334ad19cad21a70c891e755c61c287a2759d7ec452b6b7f65bbfad2a58f01c9167da5418ad75964e0e0dba52b7ddb1c6ac52fb0c

test:
  secret_key_base: 12e88b5fc5ae5420326b525ae4b6fc6a3a2d42cd5e5a595c8f495cf07a01d50d4cdf4e5102a6341dabf90f8a61af30274a9308ddfabb22af353afa543ce28d0c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
